[PowerPC]
HW_INIT_SKIP1 = 0x3003DC0
HW_INIT_SKIP2 = 0x3003E54

[General]
GPURenderThreadEnabled = true
QuitOnWindowClosure = true
Fullscreen = true
VSync = true
Loglevel = 0

[SMC]
COMPort = 2
SMCPowerOnType = 18

[GPU]
screenWidth = 2560
screenHeight = 1440

[Paths]
OneBL = "C:/Xbox/1bl.bin"
Fuses = "C:/Xbox/fuses.txt"
Nand = "C:/Xbox/nand.bin"
ODDImage = "C:/Xbox/xenon.iso"
ISO = "C:/Xbox/xenon.iso"

# Do not touch these options unless you know what you're doing!
# It can break execution! User beware.
[HighlyExperimental]
TPI = 0
